# -*- coding: utf-8 -*-
"""Week3Assignment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hA3wkySX91gPeg62DCPiUaqIAdhL0imk
"""

# Week3 Assignment-1
# Submitted by Tiya Singh, 20701012025, IGDTUW

#import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#ML libraries
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LinearRegression

# Used to split dataset into training and testing data
from sklearn.model_selection import train_test_split

# Used to evaluate classification models
from sklearn.metrics import accuracy_score, confusion_matrix

# Converts text columns into numerical values
from sklearn.preprocessing import LabelEncoder

#Part A: Understanding the Dataset

#Q1. Dataset Overview Load the dataset and answer the following:

df = pd.read_csv("agriculture_yield_dataset.csv")
#How many rows and columns are present?
print("Rows, Columns:", df.shape)
#What are the names of all columns?
print("\nColumns:\n", df.columns)
#Display the first 10 records.
print("\nFirst 10 rows:\n", df.head(10))

#Q2. Data Types and Missing Values

#Check the data type of each column.
print("\nData Types:\n", df.dtypes)
#Identify whether any missing values are present.
missing = df.isnull().sum()
print("\nMissing Values:\n", missing)
#If missing values exist, mention the affected columns.
missing = df.isnull().sum()
print("\nMissing Values:\n", missing)

#Q3. Descriptive Statistics Generate summary statistics for all numerical features and answer:

desc = df.describe()
print(desc)
#Which feature has the highest mean value?
mean_vals = df.select_dtypes(include=np.number).mean()
print("\nHighest mean feature:", mean_vals.idxmax())
#Which feature has the highest standard deviation?
std_vals = df.select_dtypes(include=np.number).std()
print("Highest std feature:", std_vals.idxmax())

#Part B: Exploratory Data Analysis (EDA)

#Q4. Distribution Analysis Create histograms for:
# rainfall_mm   temperature_c   fertilizer_kg   yield_ton_per_hectare
#Write 2–3 observations from each histogram.

cols = ["rainfall_mm", "temperature_c", "fertilizer_kg", "yield_ton_per_hectare"]
for col in cols:
    plt.figure()
    plt.hist(df[col], bins=20, edgecolor="black")
    plt.title(f"Histogram of {col}")
    plt.show()

#Q5. Crop Type Analysis  Find the number of records for each crop type.
# Create a count plot (bar chart) for crop_type.   Which crop appears most frequently?

print(df["crop_type"].value_counts())
df["crop_type"].value_counts().plot(kind="bar", title="Crop Type Count")
plt.show()
print("Most frequent crop:", df["crop_type"].value_counts().idxmax())

#Q6. Soil Type Analysis
#Find the frequency of each soil type.   Create a count plot for soil_type.
# Which soil type is most common?

print(df["soil_type"].value_counts())
df["soil_type"].value_counts().plot(kind="bar", title="Soil Type Count")
plt.show()
print("Most common soil type:", df["soil_type"].value_counts().idxmax())

#Q7. Yield Distribution Create a histogram of yield_ton_per_hectare.

plt.hist(df["yield_ton_per_hectare"], bins=20, edgecolor="black")
plt.title("Yield Distribution")
plt.show()

# Is the distribution approximately normal?   Are there any noticeable outliers
print("The yield distribution is approximately normal, as it shows a bell-shaped curve centered around the mean. There are no significant outliers, though a few slightly low and high values exist at the extremes.")

#Q8. Scatter Plot Analysis Create scatter plots of: 1. rainfall_mm vs yield_ton_per_hectare  2. fertilizer_kg vs yield_ton_per_hectare

plt.scatter(df["rainfall_mm"], df["yield_ton_per_hectare"])
plt.title("Rainfall vs Yield")
plt.xlabel("Rainfall")
plt.ylabel("Yield")
plt.show()

plt.scatter(df["fertilizer_kg"], df["yield_ton_per_hectare"])
plt.title("Fertilizer vs Yield")
plt.xlabel("Fertilizer")
plt.ylabel("Yield")
plt.show()

#Based on the plots:  Which feature appears to have a stronger relationship with yield?
print("Rainfall has a stronger relationship with yield than fertilizer as rainfall shows a more visible positive correlation with yield, while fertilizer shows a weak and scattered relationship.")

#Q9. Correlation Analysis  Generate a correlation matrix for numerical features.
# Create a heatmap.   Identify the top three features most correlated with crop yield.

import seaborn as sns
corr = df.select_dtypes(include=np.number).corr()
print(corr)
plt.figure(figsize=(8,6))
sns.heatmap(corr, annot=True, cmap="coolwarm")
plt.show()
print("Top correlated with yield:")
print(corr["yield_ton_per_hectare"].sort_values(ascending=False)[1:4])

#Q10. Group-Based Analysis Calculate the average yield for:
# Each crop type   Each soil type  Which crop and soil type have the highest average yield?

print(df.groupby("crop_type")["yield_ton_per_hectare"].mean())
print("\nBest crop:")
print(df.groupby("crop_type")["yield_ton_per_hectare"].mean().idxmax())
print("\nSoil type yield:")
print(df.groupby("soil_type")["yield_ton_per_hectare"].mean())
print("\nBest soil:")
print(df.groupby("soil_type")["yield_ton_per_hectare"].mean().idxmax())

#Part C: Data Preparation

#Q11. Feature Encoding The dataset contains categorical variables.
# Identify the categorical columns.   Convert them into numerical form using One-Hot Encoding.
# Display the first five rows of the transformed dataset.

df_encoded = pd.get_dummies(df, columns=["crop_type", "soil_type"], drop_first=True)
print(df_encoded.head())

#Q12. Feature Selection Separate:
# Input features (X)   Target variable (y)  Specify which column is being used as the target variable.

X = df_encoded.drop("yield_ton_per_hectare", axis=1)
y = df_encoded["yield_ton_per_hectare"]
print("X shape:", X.shape)
print("y shape:", y.shape)
print("Target variable is yield_ton_per_hectare")

#Part D: Machine Learning

#Q13. Train-Test Split
#Split the dataset into:  80% Training Data   20% Testing Data
#Display the shape of:  X_train   X_test   y_train   y_test

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

#Q14. Linear Regression Model
# Train a Linear Regression model.
# Display the model coefficients and intercept.   Which feature has the highest positive coefficient?

model = LinearRegression()
model.fit(X_train, y_train)

# Predictions (optional)
y_pred = model.predict(X_test)

# Coefficients + intercept
print("Intercept:", model.intercept_)

coeff_df = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": model.coef_
})

print(coeff_df.sort_values(by="Coefficient", ascending=False))

print("\nHighest positive coefficient feature:")
print(coeff_df.loc[coeff_df["Coefficient"].idxmax(), "Feature"])